-- 사용자 계정 테이블
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 출하일지 테이블
CREATE TABLE IF NOT EXISTS shipment_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  shipment_date DATE NOT NULL,
  shipper_name VARCHAR(100) NOT NULL,
  product_name VARCHAR(100) NOT NULL,
  species VARCHAR(100),
  unit_weight VARCHAR(50),
  quantity INT,
  total_boxes INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;